#!/bin/bash

# backup btrfs subvol to another btrfs filesystem
#
## Version 2.0 specs
# - user getopts()
# - separate params for snaphot, old snapshot, backup dir, renaming, date postfix

## Functions

help() {
	echo "Usage: $(basename $0) [-odh] SNAPSHOT BACKUP_DIR"
	echo -e "\t-h\tDisplay help"
	echo -e "\t-o\tOld snapshot"
	echo -e "\t-d\tAdd date suffix"
	echo -e "\t-t\tAdd datetime suffix"
	echo -e "\t-a\tRetry full backup automatically"
	echo -e "\t-r\tRemove old source snapshot"

	exit 0
}

error() {
	MSG=$1
	echo "${MSG}"
	exit 1
}

get_rand() {
	cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 4 | head -n 1 
}

do_pause() {
	SECS=$1
	[[ $SECS =~ ^-?[0-9]+$ ]] || error "do_pause(): non-integer param given"
	for ((i = 0 ; i <= $SECS ; i++)); do
		printf "."
		sleep 1
	done
}

do_backup_full() {
	if (( $# != 2 )); then
    		help
	fi
	SRC="$0"
	DST="$1"
	ionice -c 3 nice -10 btrfs send  "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" 
}

do_backup_inc() {
	if (( $# != 3 )); then
    		help
	fi
	SRC="$0"
	OLD="$1"
	DST="$2"
	ionice -c 3 nice -10 btrfs send -p "${OLD}" "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" 
}


## Params
unset OLD
unset DO_HELP
unset AUTO_RETRY
unset REMOVE
ADD_DATE_SFX=0
ADD_TIME_SFX=0
SFX=""

if (( $# < 2 )); then
    help
fi

while getopts 'hadtrs:o:' option
do
    case "$option" in
    h)
         help
         ;;
    a)
	AUTO_RETRY=1
	;;
    d)
         ADD_DATE_SFX=1
         ;;
    t)
         ADD_DATE_SFX=1
         ADD_TIME_SFX=1
         ;;
    r)
	REMOVE=1
	;;
    s)
         SFX="${OPTARG}"
         ;;
   o)
         OLD="${OPTARG}"
         ;;
    *)
        echo "Invalid argument received."
        help
        ;;
    esac
done

shift $((OPTIND-1))
OTHERARGS=$@

if (( ${#OTHERARGS[@]} != 2 )); then
   echo "Invalid arguments given. SNAPSHOT and/or BACKUP_DIR missing"
   help
fi

#################

#OLD="old"
#NEW="current"

SRC="$1"
DST_DIR="$2"
BASENAME="$(basename ${SRC})"

#### Test parameters
[ -d "${SRC}" ] &&  { echo "Source: ${SRC}" } || {  error "Source subvolume not found: ${SRC}"}
## Test for -o $OLD exists
[ -z ${OLD+x} -o  -d "${OLD}" ] || { error  "Old source subvolume -o defined, but \"${OLD}\" not found" ;}
[ -d "${DST_DIR}" ] && { echo "Destination: ${DST_DIR}";} || { error "Destination directory ${DST_DIR} not found"; } 

sync

unset FAILED

## Of -o is set
if [ ! -z ${OLD+x} ]; then
	echo "Trying to make incremental snapshot... pausing for 3 secs"
	do_pause 3

	do_backup_inc "${SRC}" "${OLD}" "${DST_DIR}" &&  echo "Incremental backup successful" || FAILED="TRUE"

	[ ! -z {FAILED+x} ] && echo "Incremental backup failed"
fi

if [ -z ${OLD+x} ] || [ ! -z ${FAILED} -a ! -z ${AUTO_RETRY} ]; then
	unset FAILED
	echo "Trying to make full backup"
	do_pause 3
	do_backup_full "${SRC}" "${DST_DIR}" && echo "Full backup successful" || FAILED="TRUE"
fi

if [ -z ${FAILED} ]; then
	BACKUP_NEW="${DST_DIR}/${BASENAME}"


else
	error "btrfs backup FAILED"
fi

#### END



if [ ! -z ${OLD+x} -a ! -z ${FAILED+x} ]; then
	echo "Incremental backup failed"
	if [ -d "$BACKUP_NEW" ]; then
		echo "Removing failed backup: ${BACKUP_NEW}"
		btrfs subvolume delete "${BACKUP_NEW}"
	fi
	FAILED="false"
	ionice -c 3 nice -10 btrfs send "${SRC}_${NEW}" | ionice -c 3 nice -10 btrfs receive "${DST_DIR}"  && echo "Full backup failed" || FAILED="true"
else
	echo "Incremental backup OK"
fi

if [ ${FAILED} = "true" ]; then
	error "BTRFS send-receive failed"
fi

## rename target subvolume
DATE=$(btrfs subvolume show "${BACKUP_NEW}" |grep "Creation time" | cut -f 4 | cut -d \  -f -1)

POSTFIX="d"
if [ "$(date --date "$DATE" +%-u)" -eq 7 ]; then POSTFIX="w"; fi
if [ "$(date --date "$DATE" +%-d)" -eq 1 ]; then POSTFIX="m"; fi
if [ "$(date --date "$DATE" +%-j)" -eq 1 ]; then POSTFIX="y"; fi

BACKUP_TARGET="${DST_DIR}/${BASENAME}_${DATE}${POSTFIX}"

if [ -d "${BACKUP_TARGET}" ]; then
 	echo "Old snapshot exists already at: ${BACKUP_TARGET}. Adding prefix.." 
	BACKUP_TARGET="${BACKUP_TARGET}_$(get_rand)"
fi
## Rename the snapshot
mv -i "${BACKUP_NEW}" "${BACKUP_TARGET}" || error "Renaming new subvolume failed ${BACKUP_NEW}"



