#!/bin/bash

# backup btrfs subvol to another btrfs filesystem
#
## Version 2.0 specs
# - user getopts()
# - separate params for snaphot, old snapshot, backup dir, renaming, date postfix
#
# v2.0: syntax OK and tests passed

## Functions

help() {
	echo "Usage: $(basename "${0}") [-hdtar] -o [OLD_SNAPSHOT]  SNAPSHOT BACKUP_DIR"
	echo -e "\t-h\tDisplay help"
	echo -e "\t-o\tOld snapshot"
	echo -e "\t-d\tAdd date suffix"
	echo -e "\t-t\tAdd datetime suffix"
	echo -e "\t-a\tRetry full backup automatically"
	echo -e "\t-r\tRemove old source snapshot"

	exit 0
}

error() {
	MSG=$1
	echo "${MSG}"
	exit 1
}

get_rand() {
	tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 4 | head -n 1 
}

do_pause() {
	SECS=$1
	[[ $SECS =~ ^-?[0-9]+$ ]] || error "do_pause(): non-integer param given"
	for ((i = 0 ; i <= SECS ; i++)); do
		printf "."
		sleep 1
	done
	echo ""
}

do_backup_full() {
	if (( $# != 2 )); then
    		error "do_backup_full(): incorrect number of params != 2 given"
	fi
	SRC="$1"
	DST="$2"
	echo "Doing full backup"
	echo "Source: ${SRC}"
	echo "Destination: ${DST}"
	ionice -c 3 nice -10 btrfs send  "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Full backup successful" 
}

do_backup_inc() {
	if (( $# != 3 )); then
    		error "do_backup_inc(): incorrect number of params != 3 given"
	fi
	SRC="$1"
	OLD="$2"
	DST="$3"
        echo "Doing incremental backup"
        echo "Source: ${SRC}"
	echo "Old snapshot: ${OLD}"
        echo "Destination: ${DST}"

	ionice -c 3 nice -10 btrfs send -p "${OLD}" "${SRC}" | ionice -c 3 nice -10 btrfs receive "${DST}" && echo "Incremental backup successful"
}

get_date_sfx() {
	if (( $# != 1 )); then
    		error "get_date_sfx(): incorrect number of params != 1 given"
        fi
        DATE="$1"

	[[ ${DATE} =~ ^[0-9-]{10}$ ]] || error "Invalid date format: ${DATE}"

	POSTFIX="d"
	[ "$(date --date "$DATE" +%-u)" -eq 7 ] && POSTFIX="w"
	[ "$(date --date "$DATE" +%-d)" -eq 1 ] && POSTFIX="m"
	[ "$(date --date "$DATE" +%-j)" -eq 1 ] && POSTFIX="y"

	echo "${DATE}${POSTFIX}"
}



## Params
unset OLD
unset DO_HELP
unset AUTO_RETRY
unset REMOVE
unset SFX
unset ADD_DATE_SFX
unset ADD_TIME_SFX


if (( $# < 2 )); then
    help
fi

while getopts 'hadtrs:o:' option
do
    case "$option" in
    h)
         help
         ;;
    a)
	AUTO_RETRY=1
	;;
    d)
         ADD_DATE_SFX=1
         ;;
    t)
         ADD_DATE_SFX=1
         ADD_TIME_SFX=1
         ;;
    r)
	REMOVE=1
	;;
    s)
         SFX="${OPTARG}"
         ;;
   o)
         OLD="${OPTARG}"
         ;;
    *)
        echo "Invalid argument received."
        help
        ;;
    esac
done

shift $((OPTIND-1))
OTHERARGS=( "$@" )

if (( ${#OTHERARGS[@]} != 2 )); then
   echo "Invalid arguments given. SNAPSHOT and/or BACKUP_DIR missing"
   help
fi

#################

#OLD="old"
#NEW="current"

SRC="$1"
DST_DIR="$2"
BASENAME="$(basename "${SRC}")"

#### Test parameters
if [ -d "${SRC}" ]; then
	echo "Source: ${SRC}"
else
	error "Source subvolume not found: ${SRC}"
fi
## Test for -o $OLD exists
if [ -n "${OLD}" ] && [ ! -d "${OLD}" ]; then
	error  "Old source subvolume -o defined, but ${OLD} not found"
fi
if [ -d "${DST_DIR}" ]; then
	echo "Destination: ${DST_DIR}" 
else
	error "Destination directory ${DST_DIR} not found"
fi

sync

unset FAILED

## Of -o is set
if [ -n "${OLD}" ]; then
	echo "Making an incremental snapshot... pausing for 3 secs"
	do_pause 3

	do_backup_inc "${SRC}" "${OLD}" "${DST_DIR}" || FAILED="TRUE"

	[ -n "${FAILED}" ] && echo "Incremental backup failed"
fi

if [ -z "${OLD}" ] || [ -n "${FAILED}" -a -n "${AUTO_RETRY}" ]; then
	unset FAILED
	echo "Making a full backup"
	do_pause 3
	do_backup_full "${SRC}" "${DST_DIR}" || FAILED="TRUE"
fi

if [ -z "${FAILED}" ]; then
	BACKUP_NEW="${DST_DIR}/${BASENAME}"
	[ -d "${BACKUP_NEW}" ] || error "Cannot find backup snapshot"
	if [ -n "${ADD_DATE_SFX}" ]; then
		[ -z "${SFX}" ] && SFX="_"
		DATE=$(btrfs subvolume show "${BACKUP_NEW}" |grep "Creation time" | cut -f 4 | cut -d \  -f 1)
		SFX="${SFX}$(get_date_sfx "${DATE}")"
	fi
	if [ -n "${ADD_TIME_SFX}" ]; then
		TIME=$(btrfs subvolume show "${BACKUP_NEW}" |grep "Creation time" | cut -f 4 | cut -d \  -f 2 | tr -d : )
		SFX="${SFX}_${TIME}"
	fi

	if [ -n "${SFX}" ]; then
		echo "Renaming snapshot"
		BACKUP_TARGET="${BACKUP_NEW}${SFX}"
		if [ -d "${BACKUP_TARGET}" ]; then
		        echo "Old snapshot exists: ${BACKUP_TARGET}. Adding prefix..."
		        BACKUP_TARGET="${BACKUP_TARGET}_$(get_rand)"
		fi
		mv -v "${BACKUP_NEW}" "${BACKUP_TARGET}" || error "Renaming new subvolume failed ${BACKUP_NEW}"
	fi
	[ -n "${REMOVE}" ] && echo "Removing old snapshot: ${OLD}" && btrfs subvolume delete "${OLD}" 
else
	error "btrfs backup FAILED"
fi

#### END

