#!/bin/bash

HONEYPOT_LOG='/var/log/nft-honeypot.log'
PTR_HONEYPOT='NFT honeypot:'
F2B_JAIL="sshd"
SED_PTRN="s/.+${PTR_HONEYPOT}.+SRC=([0-9\.]+).+/\1/p"

## Functions
TUPA_UTILS="$(dirname "${0}")/tupa-utils"
# shellcheck source=./tupa-utils
{ [ -f "${TUPA_UTILS}" ] && source "${TUPA_UTILS}";} || exit 1


help() {
	echo "Usage: $(basename "$0") [-r]"
	echo -e "\t-h\tDisplay help"
	echo -e "\t-r N\tReload N latest IPs from log"
	echo -e "\t-R\tReload all IPs from log"
	echo -e "\t-m\tMonitor IPs from log"
	exit 0
}

monitor_log() {
	tail -n 0 -f "${HONEYPOT_LOG}" | sed -unE "${SED_PTRN}" |xargs -rI {} fail2ban-client set "${F2B_JAIL}" banip {}
}

reload_log_all() {
	<"${HONEYPOT_LOG}" sed -nE "${SED_PTRN}" | sort |uniq |xargs -n 50 fail2ban-client set "${F2B_JAIL}" banip
}

reload_log() {
	N="$1"
	tail -n "$N" "${HONEYPOT_LOG}" | sed -nE "${SED_PTRN}" | sort |uniq |xargs -n 50 fail2ban-client set "${F2B_JAIL}" banip
}

## main()
if (( "$#" == 0 )); then
    help
fi


DO_RELOAD=0
DO_RELOAD_ALL=0
DO_MONITOR=0

while getopts ':r:Rhm' option
do
    case "$option" in
    h)
         help
         ;;
    m)
         DO_MONITOR=1
         ;;
    r)
	DO_RELOAD="${OPTARG}"
	if  [ ! "$DO_RELOAD" -gt 0 ] 2> /dev/null; then
		error "correct syntax is: \"-r N\", where N is a positive INTEGER"
	fi
	;;
    R)
         DO_RELOAD_ALL=1
         ;;
    *)
        echo "Invalid argument received."
        help
        exit 1
        return
        ;;
    esac
done

if [ ! -f "${HONEYPOT_LOG}" ]; then
	echo "Honeypot log (${HONEYPOT_LOG}) not found"
	exit 1
fi


if [ "$DO_RELOAD_ALL" -eq 1 ]; then
	reload_log_all
elif [ "$DO_RELOAD" -gt 0 ]; then
	reload_log "${DO_RELOAD}"
fi 

if [ "$DO_MONITOR" -eq 1 ]; then
	monitor_log
fi
