#!/usr/bin/env bash
# Shows a spinner while another command is running. Randomly picks one of 12 spinner styles.
# @args command to run (with any parameters) while showing a spinner.
#       E.g. ‹spinner MODE sleep 10›
# Copyright: Jonas Eberle https://unix.stackexchange.com/a/565551

function shutdown() {
  tput cnorm # reset cursor
}
trap shutdown EXIT

function cursorBack() {
  echo -en "\033[$1D"
  # Mac compatible, but goes back to first column always. See comments
  #echo -en "\r"
}

function spinner() {
  # make sure we use non-unicode character type locale
  # (that way it works for any locale as long as the font supports the characters)
  local LC_CTYPE=C

  local MODE="$1"
  local pid="$2" # Process Id of the previous running command
  case "${MODE}" in
  dots)
    local spin='⠁⠂⠄⡀⢀⠠⠐⠈'
    local charwidth=3
    ;;
  lines)
    local spin='-\|/'
    local charwidth=1
    ;;
  hbar)
    local spin="▁▂▃▄▅▆▇█▇▆▅▄▃▂▁"
    local charwidth=3
    ;;
  vbar)
    local spin="▉▊▋▌▍▎▏▎▍▌▋▊▉"
    local charwidth=3
    ;;
  arrows)
    local spin='←↖↑↗→↘↓↙'
    local charwidth=3
    ;;
  cubes)
    local spin='▖▘▝▗'
    local charwidth=3
    ;;
  corners)
    local spin='┤┘┴└├┌┬┐'
    local charwidth=3
    ;;
  halfs)
    local spin='◐◓◑◒'
    local charwidth=3
    ;;
  digi)
    local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
    local charwidth=3
    ;;
  clock)
    local spin='🕛🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚'
    local charwidth=2
    ;;
  esac

  local i=0
  tput civis # cursor invisible
  while kill -0 "${pid}" 2>/dev/null; do
    local i=$(((i + "${charwidth}") % "${#spin}"))
    printf "%s" "${spin:$i:$charwidth}"

    cursorBack 1
    sleep .1
  done
  tput cnorm
  wait "${pid}" # capture exit code
  return $?
}

MODE="$1"
case "${MODE}" in

    "--help")
    printf "Usage: spinner [MODE] COMMAND [ARGS]\n" >&2
    printf "  MODE: dots | lines | hbar | vbar | arrows | cubes | corners | halfs | digi | clock\n" >&2
    exit 1
    ;;

  dots|lines|hbar|vbar|arrows|cubes|corners|triangles|pies|halfs|digi|clock)
    shift
    ;;

  *)
  MODE="lines"
  ;;
esac

("$@") &

spinner "${MODE}" $!
