# backup-mongodb

# Mongod auth
M_USER="backup"
M_PASSWD="password_here"
M_HOST="hostname.domain"
M_CA="/etc/ssl/CA.pem"
C_CERT="/etc/ssl/client.pem"
AUTH_DB="admin"
DB="db_name"

## 
ARCHIVE_DIR="/var/backup/mongodb"

