#!/usr/bin/env bash

# send btrfs subvols to another btrfs filesystem

# shellcheck disable=SC2034
VERSION="2.1.2"

## Version 2.0 specs
# - user getopts()
# - separate params for snaphot, old snapshot, backup dir, renaming, date postfix
#
# v2.0: syntax OK and tests passed

## Functions

help() {
	echo "btrfs send-receive subvolumes using parent volumes"
	echo "Usage: btrfs-send [-hqvf] [-p PROTO] [TARGET_DIR] [SNAPSHOT1 ..]"
	echo -e "\t-h\t\tDisplay help"
	echo -e "\t-q\t\tQuiet operations"
	echo -e "\t-v\t\tVerbose operations"
	echo -e "\t-p PROTO\tProtocol version (btrfs send --proto N)"
	echo -e "\t-f\t\tDo full send-receive for the first snapshot"

	exit 0
}

error() {
        MSG="${1}"
        echo "Error: ${MSG}"
        exit 1
}

## Params
VERBOSE=()
FULL=""
PROTO=0

# shellcheck disable=SC2220
while getopts 'hqvfp:' option
do
    case "$option" in
    h)
         help
         ;;
    q)
         VERBOSE=(-q)
         ;;
    v)
         VERBOSE=(-v)
         ;;
    f)
         FULL='yes'
         ;;
    p)
         PROTO="${OPTARG}"
         ;;

    esac
done

shift $((OPTIND-1))
ARGS=( "$@" )

if (( ${#ARGS[@]} < 2 )); then
	echo "ERROR: Too few parameters"
	help
fi

TARGET_DIR="${ARGS[0]}"
unset 'ARGS[0]'
ARGS=( "${ARGS[@]}")

# do full snapshot
LEN=${#ARGS[@]}
if [ -n "${FULL}" ]; then
	# shellcheck disable=SC2004
	if (( $LEN < 1)); then
        	error "Too few arguments"
        fi
	echo "btrfs (full) send/receive: ${ARGS[0]} => ${TARGET_DIR}"
        btrfs "${VERBOSE[@]}" send --proto "${PROTO}" "${ARGS[0]}" | btrfs "${VERBOSE[@]}" receive "${TARGET_DIR}"
fi

while true; do
	LEN=${#ARGS[@]}
	# shellcheck disable=SC2004
	if (( $LEN <= 1 )); then
		echo "Done"
		break
	fi
	echo "btrfs (partial) send/receive: (parent=${ARGS[0]}) ${ARGS[1]} => ${TARGET_DIR}"
	btrfs "${VERBOSE[@]}" send --proto "${PROTO}" -p "${ARGS[0]}" "${ARGS[1]}" | btrfs "${VERBOSE[@]}" receive "${TARGET_DIR}"
	unset 'ARGS[0]'
	ARGS=( "${ARGS[@]}")
done
