#!/bin/sh

TRIMCMD="/usr/local/sbin/trim-archives"

## Docs
${TRIMCMD} -b -d=45 -w=16 -m=18 -y=3 -H=36 -f /home/backup/localhost/jarno/@snapshot

## SYSTEM
${TRIMCMD} -b -d=7 -w=6 -m=0 -y=0 -f   /var/backups/system/@snapshot

## Archive
${TRIMCMD} -b -d=10 -w=8 -m=6 -y=2 -f   /home/backup/localhost/Archive/@snapshot

