#!/usr/bin/env bash

SOURCE=
TARGET=
POSTFIX=""
RW=""
BACKUP_ROOT=

DATE="$(date '+%F')"

# man date:
#	%u     day of week (1..7); 1 is Monday
#	%d     day of month (e.g., 01)
#	%j     day of year (001..366)
#	%-     removes padding (spaces or zeroes)


help() {

echo "Usage: $(basename "$0") [-h|q|w] [-b BACKUP_ROOT] SOURCE TARGET"
echo -e "\t-h\t\tDisplay help"
echo -e "\t-w\t\tTake R/W snapshot"
echo -e "\t-p y|q|m|w|d|h \tSet snapshot postfix"
echo -e "\t-b BACKUP_ROOT\tSet backup root directory"
}


error() {
	echo "$1"
	exit 1
}

# shellcheck disable=SC2220
while getopts 'hwb:p:' option
do
	case "$option" in
		h)
			help
			exit 0
		;;
		w)
			RW="y"
		;;
    b)
      BACKUP_ROOT="${OPTARG}"
        ;;
		p)
			case "${OPTARG}" in
				y) POSTFIX="y";;
				m) POSTFIX="m";;
				q) POSTFIX="q";;
				w) POSTFIX="w";;
				d) POSTFIX="d";;
				h)
				  HOUR="$(date '+%H%M')"
				  POSTFIX="_${HOUR}h"
				;;
				*) echo "invalid -p option: ${OPTARG}"
			esac
		;;
	esac
done

# Read rest of the params
shift "$(( "$OPTIND" - 1 ))"

if [[ "$#" -eq 2 ]]; then
# || { [[ "$#" -ne 1 ]] && [[ -n "${BACKUP_ROOT}" ]] ;}; then
	SOURCE="${1}"
	TARGET="${2}"

elif [[ "$#" -eq 1 ]] && [[ -n "${BACKUP_ROOT}" ]]; then
	SOURCE="${1}"
	BASENAME="$(basename "${SOURCE}")"
	TARGET="${BASENAME}/@snapshot_${BASENAME}"

else
	echo "Incorrect number of arguments"
	help
	exit 1
fi

if [[ -n "${BACKUP_ROOT}" ]] ; then
	TARGET="${BACKUP_ROOT}/${TARGET}"
fi

if [ -z "${POSTFIX}" ]; then
	POSTFIX="d"
	if [ "$(date --date "$DATE" +%-u)" -eq 7 ]; then POSTFIX="w"; fi
	if [ "$(date --date "$DATE" +%-d)" -eq 1 ]; then POSTFIX="m"; fi
	if [ "$(date --date "$DATE" +%-j)" -eq 1 ]; then POSTFIX="y"; fi
fi

TARGET="${TARGET}_${DATE}${POSTFIX}"
TARGET_DIR="$(dirname "${TARGET}")"

if [[ ! -d "${TARGET_DIR}"  ]]; then
	mkdir -p "${TARGET_DIR}" || error "Could not create target dir: ${TARGET_DIR}"
fi

if [[ ! -w "${TARGET_DIR}"  ]]; then
	error  "Cannot write to target dir: ${TARGET_DIR}"
fi


if [[ -z "${RW}" ]]; then
	btrfs subvolume snapshot -r "${SOURCE}" "${TARGET}"
else
	btrfs subvolume snapshot "${SOURCE}" "${TARGET}"
fi
