#!/bin/sh

## Script to update Unifi Controller

## Functions
TUPA_UTILS="$(dirname "${0}")/tupa-utils"
# shellcheck source=./tupa-utils
{ [ -f "${TUPA_UTILS}" ] && source "${TUPA_UTILS}";} || exit 1

pushd /usr/local/docker/unifi || error "Cannot change to /usr/local/docker/unifi"
docker-compose pull unifi-controller
docker-compose up -d unifi-controller
popd
