#!/bin/bash

## Script to update apps running docker swarm 

## Functions
TUPA_UTILS="$(dirname "${0}")/tupa-utils"
# shellcheck source=./tupa-utils
{ [ -f "${TUPA_UTILS}" ] && source "${TUPA_UTILS}";} || exit 1

help() {
        echo "Usage: $(basename "${0}") [-h|--help] APP"
        echo -e "\t-h|--help\tDisplay help"
        echo -e "\tAPP\tDocker application to update"
        exit 0
}


[[ "${1}" == "-h" || "${1}" == "help" || "${1}" == "--help" ]] && help

APP="${1}"
[[ "${APP}" =~ ^[[:alnum:]_\-]+ ]]; echo "${BASH_REMATCH[0]}"

[[ "${APP}" =~ ^[[:alnum:]_\-]+ ]]
[[ "${APP}" == "${BASH_REMATCH[0]}" ]] || error "Invalid application: ${APP}"

pushd /usr/local/docker/"${APP}" || error "Cannot change to /usr/local/docker/${APP}"
docker-compose pull "${APP}"
docker-compose up -d "${APP}"
popd || error "Could not return to working dir"
