#!/bin/bash

## Functions

TUPA_UTILS="$(dirname "${0}")/tupa-utils"
# shellcheck source=./tupa-utils
{ [ -f "${TUPA_UTILS}" ] && source "${TUPA_UTILS}";} || exit 1


help() {
    echo "Usage: $(basename "$0") [-hqdcum] [-b DIR] DIR [DIR1 ...]"
    echo -e "\t-h\t\tDisplay help"
    echo -e "\t-q\t\tDo not print checksums"
    echo -e "\t-c\t\tCheck existing checksums"
    echo -e "\t-m\t\tUpdate missing checksums"
    echo -e "\t-u\t\tUpdate changed checksums"
    echo -e "\t-d\t\tAdd date to previous checksum version"
    echo -e "\t-b DIR\tBase directory for the operations"
#    echo -e "\t-A FILE\tFilename for aggregate file"
    exit 0
}

file_modified() {
	FILE="${1}"
	date -r "${FILE}" +"%Y%m%d"
}

if [ ${#} -eq 0 ]; then
    help
fi

MODE="create"
QUIET=
BASEDIR=
DATE=
CHECKSUM=".checksum"

declare -a ALGO

while getopts 'hqdcumb:a:' option
do
# shellcheck disable=SC2220
    case "$option" in
    h)
         help
         ;;
    q)
        QUIET="--quiet"
        ;;
    c)
        MODE="check"
         ;;
    m)
        MODE="missing"
         ;;
    u)
        MODE="update"
         ;;
    d)
        DATE="yes"
         ;;
    a)
	case "${OPTARG}" in
		b3)
			ALGO+=( "b3" )
		;;
		sha256)
			ALGO+=("sha256" )
		;;
		sha512)
			ALGO+=( "sha512" )
		;;
		md5)
			ALGO+=( "md5" )
		;;
		*)
			error "Unknown hash algorithm ${OPTARG}"
		;;
	esac
	;;
    b)
        BASEDIR="${OPTARG}"
        ;;
    esac
done

if (( ${#ALGO[@]} == 0 )); then
    ALGO+=( "b3" )
fi


# Read rest of the params
shift "$(( "$OPTIND" - 1 ))"

declare -a DIRS

while test "$#" -gt 0; do
        if [ -d "${1}" ]; then
                DIRS+=( "${1}" )
        fi
        shift
done

if [ -n "${BASEDIR}" ]; then
	pushd  "${BASEDIR}" > /dev/null || error "Cannot change into ${BASEDIR}" 
fi

set -u
for dir in "${DIRS[@]}"; do
	# cd "${dir}" || continue
	while read -r d; do
		pushd "${d}"  > /dev/null || continue
		echo "# Directory: ${d}"
		for alg in "${ALGO[@]}"; do
			CHECKSUM_FILE="${CHECKSUM}.${alg}"
			if  [ "${MODE}" = "missing" ] && [ -s "${CHECKSUM_FILE}" ]; then
				verbose "${d} : Skipping"
				continue
			fi

			if [ "${MODE}" = "check" ]; then
 				if [ -n "${QUIET}" ]; then
					"${alg}sum"  --check --quiet "${CHECKSUM_FILE}"
				else
					"${alg}sum"  --check "${CHECKSUM_FILE}"
				fi
				continue
			fi

			if (( $(find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" | wc -l) == 0)); then
				[ -f "${CHECKSUM}.tmp" ] && rm "${CHECKSUM}.tmp"
				touch "${CHECKSUM}.tmp"
			elif [ -n "${QUIET}" ] ||[ "${MODE}" = "update" ]; then
				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- > "${CHECKSUM}.tmp"
			else
				find . -maxdepth 1 -type f ! -name "${CHECKSUM}.*" -printf '%P\0' | xargs -0 "${alg}sum" -- | tee "${CHECKSUM}.tmp"
			fi

			if [ "${MODE}" = "update" ] && [ -f "${CHECKSUM_FILE}" ]; then
				# keep the old checksum file if there isn't any difference
				diff "${CHECKSUM_FILE}" "${CHECKSUM}.tmp" && continue
			fi

			if [ -n "${DATE}" ] && [ -f "${CHECKSUM_FILE}" ]; then
				mv "${CHECKSUM_FILE}" "${CHECKSUM_FILE}_$(file_modified "${CHECKSUM_FILE}")"
			fi

			mv "${CHECKSUM}.tmp" "${CHECKSUM_FILE}"
			# delete empty checksum files
			[ ! -s "${CHECKSUM_FILE}" ] && rm "${CHECKSUM_FILE}"

		done
		popd > /dev/null || error "Could not return to dir"
	done < <(find  "${dir}" -type d)
done

if [ -n "${BASEDIR}" ]; then
	popd > /dev/null  || error "Could not return to dir"
fi

