#!/bin/bash

# Makes READONLY btrfs snapshots to BACKUP_ROOT/DIR  (e.g. /home/backup/localhost/Flac)
# Changelog
# 2014-10-18: changed snapshots to readonly (-r option)
# 2021-08-07: rewrite 

CONFIG_FILE="~/.config/tupa-utils"

BACKUP_ROOT=/home/backup/localhost

if [ -f "${CONFIG_FILE}" ]; then
	.  "${CONFIG_FILE}"
fi

declare -a DIRS
DATE=`date '+%F'`

# man date:
#	%u     day of week (1..7); 1 is Monday
#	%d     day of month (e.g., 01)
#	%j     day of year (001..366)
#	%-     removes padding (spaces or zeroes)

POSTFIX="d"
if [ $(date --date $DATE +%-u) -eq 7 ]; then POSTFIX="w"; fi
if [ $(date --date $DATE +%-d) -eq 1 ]; then POSTFIX="m"; fi
if [ $(date --date $DATE +%-j) -eq 1 ]; then POSTFIX="y"; fi

SILENT=""

help() {

echo "Usage: $(basename $0) [-h] [-c CONFGIG_FILE] [DIR DIR1 ...]"
echo -e "\t-h\tDisplay help"
echo -e "\t-c FILE\tRead configuration from FILE"

exit 0
}

while getopts ':hb:c:' option
do
	case "$option" in
		h)
			help
		;;
		b)
			BACKUP_ROOT="${OPTARG}"
		;;
	    	c)
			if [ -f "${OPTARG}" ]; then
				while IFS= read -r DIR; do
					DIRS+=( "${DIR}" )
				done < "${OPTARG}"
			fi
		;;
	esac 
done

# Read rest of the params
shift $(expr $OPTIND - 1 )

while test $# -gt 0; do
	echo "ARG: $1"
	if [ -d "${1}" ]; then 
		DIRS+=( "${1}" )
	fi
	shift
done

for dir in ${DIRS}; do
	NAME=`basename "$dir"`
	echo "Snapshotting ${dir}"
	btrfs subvolume snapshot -r "${dir}" "${BACKUP_ROOT}/${NAME}/@snapshot_${NAME}_${DATE}${POSTFIX}"
done
