#!/bin/sh
if [ $# -ne 1 ] || [ "$1" = "-h" ]; then
	echo "Usage: $(basename "$0") app_name"
	exit 1
fi

APP="$1"

systemctl stop --user "podman-pod@${APP}.service" || exit 2
~/"init_pod_${APP}" || exit 3
systemctl stop --user "podman-pod@${APP}.service" || exit 4
