#!/usr/bin/env bash

## Helper for par2 command

VERSION="0.1.1"

## Functions

help() {
	echo "par2 helper to create and update parchive2 redundancy files"
	echo "Usage: $(basename "${0}") [-hRrclu] DIR [DIR1 ...]"
	echo -e "\t-h\tDisplay help"
	echo -e "\t-r PERCENT\tRedundancy ratio% as whole integer (default 5)"
	echo -e "\t-R\tCreate recursive archive including DIR subdirectories"

	echo -e "\t-l\tList status by DIR"
	echo -e "\t-u\tUpdate PAR2ARCHIVE in DIR"
	echo -e "\t-c\tCreate PAR2ARCHIVE for DIR"
	echo -e "\t-v\tVerify PAR2ARCHIVE in DIR"

	echo -e "Version: ${VERSION}"
	exit 0
}

error() {
        MSG="${1}"
        echo "Error: ${MSG}"
        exit 1
}


par2file() {
	local PAR2FILE
	PAR2FILE="$(find . -maxdepth 1 -type f -iname '*.par2' | sort  | head -n 1)"
	echo "${PAR2FILE}"
}


list_newer() {
	find . -maxdepth 1 -type f -newer "${1}" ! -iname "*.par2" ! -name ".*"
}


list_files() {
	find . -maxdepth 1 -type f ! -iname "*.par2" ! -name ".*"
}


par2tool_list() {
	# list status of dir
	local DIR
	local PAR2FILE
	DIR="$(pwd)"
	PAR2FILE="$(par2file "${DIR}")"
	if [ ! -f "${PAR2FILE}" ]; then
		if (( $(list_files | wc -l) > 0 )); then
			echo "${DIR}: ERROR: No par2 file"			
		fi
	else
		 if (( $(list_newer "${PAR2FILE}" | wc -l) > 0 )); then
            echo "${DIR}: ERROR: Update needed"
			if [ -z "${QUIET}" ]; then
				list_newer "${PAR2FILE}"
			fi
         else
			echo "${DIR}: OK"
		fi
	fi # if PAR2FILE exists
} # par2tool_list()


par2tool_verify() {
	# verify dir
	local DIR
	local PAR2FILE
	DIR="$(pwd)"
	PAR2FILE="$(par2file "${DIR}")"
	if [ ! -f "${PAR2FILE}" ]; then
		if (( $(list_files | wc -l) > 0 )); then
			error "${DIR}: No par2 file"			
		fi
	else
		 if (( $(list_newer "${PAR2FILE}" | wc -l) > 0 )); then
            error "${DIR}: Update needed"			
         else
			par2verify -q "${PAR2FILE}" | grep -vE '(- found\.$|^Loading)'
			if [ "${PIPESTATUS[0]}" -ne 0 ]; then
				error "${DIR}: par2verify failed"
			fi
		fi
	fi # if PAR2FILE exists
} # par2tool_verify()


par2tool_update() {
	# list status of dir
	local DIR
	local PAR2FILE
	DIR="$(pwd)"
	PAR2FILE="$(par2file "${DIR}")"
	if [ ! -f "${PAR2FILE}" ]; then
		if (( $(list_files | wc -l) > 0 )); then
			par2tool_create
		fi
	else
		if (( $(list_newer "${PAR2FILE}" | wc -l) > 0 )); then
            par2tool_create
        else
			echo "${DIR}: OK"
		fi
	fi # if PAR2FILE exists
} # par2tool_update()



par2tool_create() {
	local DIR
	DIR="$(pwd)"
	if [ -z "${RECURSIVE}" ]; then
		find . -maxdepth 1 -type f -name "*.par2" -delete
		par2create -q -u "-r${RATIO}" "$(basename "${DIR}").par2" ./*
	else
		find . -type f -name "*.par2" -delete
		par2create -q -u "-r${RATIO}" -R "$(basename "${DIR}").par2" ./*
	fi #  if RECURSIVE
}


## Params
RECURSIVE=""
RATIO=5
ACTION="list"
QUIET=""

# shellcheck disable=SC2220
while getopts 'hqcluvRr:' option
do
    case "$option" in
    h)
         help
         ;;
    r)
         RATIO="${OPTARG}"
         ;;
    R)
         RECURSIVE='yes'
         ;;
    q)
         QUIET='--quiet'
         ;;
    l)
         ACTION='list'
         ;;
    c)
         ACTION='create'
         ;;
    u)
         ACTION='update'
         ;;
    v)
         ACTION='verify'
         ;;
    esac
done

if (( RATIO < 1 || RATIO > 100)); then
	error "-r RATIO must be between 1-100"
fi

shift $((OPTIND-1))
DIRS=( "$@" )

if (( ${#DIRS[@]} == 0 )); then
	echo "ERROR: no DIR given"
	help
fi

for dir in "${DIRS[@]}"; do
	pushd "${dir}" > /dev/null || continue
	echo "$dir:"
	case "${ACTION}" in
	list)
		par2tool_list "${dir}"
		;;
	create)
		par2tool_create "${dir}"
		;;
	update)
		par2tool_update "${dir}"
		;;
	verify)
		par2tool_verify "${dir}"
		;;
	*)
		error "unknown action ${ACTION}"
		;;
	esac
	popd  > /dev/null || error "Could not return to previous dir"
done